### Get a specific book (tested)

GET  /api/books/{isbn} 
Host: localhost:8080
Accept: application/json

### search books by keyword (tested)
GET  /api/books/search/{keyword}
Host: localhost:8080
Accept: application/json

### Get all genres (tested)

GET  /api/books/genre
Host: localhost:8080
Accept: application/json

### Get books by genre (tested)

GET  /api/books/genre/{genre}
Host: localhost:8080
Accept: application/json

### Get books sorted by filter and order(desc/asc) (tested)

GET  /api/books/{filter}/{order}
Host: localhost:8080
Accept: application/json

### Borrrow a book
GET  /api/books/{isbn}/borrow
Host: localhost:8080
Accept: application/json

### Login (tested)

POST /api/users/login
Host: localhost:8080
Content-Type: application/json

{
    "email": "sandrich0@omniture.com",
    "password": "nVxvMrpU"
}

### register a new user (tested)

POST /api/users/register
Host: localhost:8080
Content-Type: application/json

{
    "email": "ghaiK9@gmail.com",
    "password": "mysql",
    "fullname": "Kanav Ghai"
}



### Add Review (tested)

POST /api/books/{isbn}/reviews
Host: localhost:8080
Content-Type: application/json
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJGbG9yaWRhIFBpbmNoaW4iLCJpZCI6MiwiZXhwIjoxNjIxMTk5NzM2LCJpYXQiOjE2MjExOTYxMzZ9.N_kcZcAbTy1sKv4PUDoBgU4iAejebElHjLr4QXC1bdE

{
    	"issueId": 202101,
	"review": "Nice Book!",
	"rating": 6
}

### Pay fine (tested)

GET  /api/users/payFine
Host: localhost:8080
Accept: application/json
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJGbG9yaWRhIFBpbmNoaW4iLCJpZCI6MiwiZXhwIjoxNjIxMjM2Nzg2LCJpYXQiOjE2MjEyMzMxODZ9.3PRDFB_rFeD-WamOZgm-y1H2axvcke_-Xsx9vd2lX1k

### Request book (tested)
POST  /api/books/request	
Host: localhost:8080
Content-Type: application/json
Authorization: "Auth token from login"

{
	"title" : "lorem ipsum",
	"author" : "some author"
}

### Edit reviews and rating (tested)
PUT /api/books/{isbn}/reviews/{reviewId}
Host: localhost:8080
Content-Type: application/json
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJGbG9yaWRhIFBpbmNoaW4iLCJpZCI6MiwiZXhwIjoxNjIxMjUyNTMyLCJpYXQiOjE2MjEyNDg5MzJ9.qHJe-D-NVo1QR-cIseyiJ4bnTtkBK_o5kTidwlJQQn8

{
	"review": "All of us really enjoyed the book - it does have a sort of ''Gone Girl'' feel, but I liked that book too.  I think the characters are interesting and although I did figure out a portion of the ending, I had to keep reading to see if I was correct.  This was a book club read and I think there is plenty to discuss at our meeting.",
	"rating": 7
}

### display previously borrowed books (tested)

GET  /api/users/borrowedBooks
Host: localhost:8080
Accept: application/json
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJGbG9yaWRhIFBpbmNoaW4iLCJpZCI6MiwiZXhwIjoxNjIxMjc0ODQ5LCJpYXQiOjE2MjEyNzEyNDl9.gP8bXGB9Sswiu9ylngbHgGSe8QhqZLxbpFIEr2kFzdI



