create table REVIEWS (
	id INT,
	ISSUE_ID VARCHAR(7),
	RATING INT,
	REVIEW VARCHAR(5476)
);
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32056, 202135, 3, 'Thought I was going to love this book! It was so popular and I saw so many people reading it. I waited a bit before reading it because I wanted the perfect beach book. So disappointed. Confusing layout of chapters going between characters and timelines. Confusing storyline with back & forth character side stories. I''ll wait until this author writes a second book & give her another chance.');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32057, 202119, 3, 'I was thoroughly confused at first because I did not notice the heading at the beginning of each chapter.  I thought the story was being narrated by the same person and it made no sense.  Then I happened to glance at top and there was the name of the person "talking"!  Completely made a difference.  Once that was established I was able to make mental conjectures that came out  the way I expected.  Well written and an interesting twist in the inter-woven lives of the people the girl on the train saw.  Have recommended it to others.');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32058, 202120, 4, 'Even though Rachel depressed me I couldn''t stop reading this and I didn''t know why. Then I realized that she was who I used to be in some ways. I was married to a very psychologically abusive man for almost thirty years before I escaped. So many of the negative things people said about Rachel explain why this kind of abuse is hard to escape. Nobody believes you. You look bitter and crazy. People say but look how fat she got. The abuser blames you and you and everyone else believes it. If you went to the authorities what would you say? He''s mean to me? They would treat you like Riley treats Rachel. It''s a horrible problem and I''m glad Ms Hawkins is bringing it to light!! Thank you thank you thank you.');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32059, 202120, 4, 'Great novel, I couldn''t put it down, can''t wait to see the movie with Emily Blunt, one of my favorite actresses');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32060, 202149, 5, 'The beginning of the book was awesome. I was hooked, but as the plot started to untwist I lost a little interest. I still finished it through but felt it went a little too "lifetime movie" for my taste.');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32061, 202101, 2, 'Ugh. This book reminded me so much of Gone Girl. I think I''m one of the only people I know that hasn''t liked either. Both of them I did finish because I wanted to know how they ended. This book was a little more satisfying at the end, but not by much. I found myself not LIKING any of the characters. I couldn''t pull for anyone, because they were all so unlikable. In the beginning, the main character makes up stories about strangers she sees regularly. Who with an imagination hasn''t done that? After that, the story becomes rather far fetched. If you''re bored and need something to read because you''ve read all the books by your favorite authors, then try this. Otherwise, there are many better bets out there. I just finished What She Left Behind. Loved that!');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32062, 202123, 1, 'Beware, before you know it you will be sucked into this story and won''t be released until you read the last page. Even then, you''ll be thinking of the story long after reading the last page. In the beginning, it was a little difficult to determine just who was narrating and about whom but the writing was such that you kept going. I would imagine most people who ride a train or bus that stops routinely, fantasize about the people they see or who lives in the homes they pass. This story takes that premise one step further when one of the people disappears. The prose is easy to read, descriptive with good character development and the plot twists and turns may give you whiplash. The Girl on the Train is a really good read.');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32063, 202140, 1, 'Holy. Cow. What an incredible, edge of your seat kind of book. This book reminded me somewhat of Gone Girl, but it was not as vulgar. If you love thrillers or mystery books that continue to keep you guessing then you should read this book! It was incredible! The first couple chapters were confusing for me, but I finally figured it out. Pay attention to the dates and also who the chapter is focusing on, hint: the name of the chapter is the name of the person that chapter focuses on. :) Great book! I loved reading this and would recommend it to anyone who loves a little psychological thrill!');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32064, 202137, 2, 'At first I found the book a bit difficult to follow because it jumped from character to character and dates kept changing with the change of characters. I quickly realized I had to pay attention to which character and what the date was when going to a new chapter.  But I found the book intriguing from the first page. I couldn''t put it down. Well written - - a great mystery.');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32065, 202144, 1, 'This is a good book!  It is fast paced, and goes from one character to the other by chapter.  I did find it a bit confusing at first but once I read more I was able to navigate the flow of the book.  The story of intertwining the female characters is an effective method for building the tension in the story.  The ending is a bit predictible but good.  I recommend.');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32066, 202111, 2, 'I read the description and couldn''t wait to start reading, unfortunately I was disappointed. All of the characters are hard to like and the whole time I was waiting for something to happen. There isn''t some crazy twist that you can''t see coming and most of the excitement is the very last chapter of the book.Honestly, it was just kind of ok.');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32067, 202103, 2, 'A good read, but a bit confusing going back and forth among the characters. Read it at a busy time, so I would start and stop. Would have been a better if I had read the book without so many interruptions. Several of my friends have put it aside as they couldn''t "get into it". Looking over the plot, I think it is a good story.');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32068, 202117, 3, 'This one kept me turning the pages.  It presents you with a cast of characters who''s lives have touched.  They are all woven together by the relentless imagination of one alcoholic and tragically lonely women, Rachel.  While you know that she has an active imagination you go right along with her as she attempts to make sense out of her rudderless life.  She manages to drag her ex-husband and his family into her drama and a couple that lives a few doors down as well.  Every day brings just a little more information to the light.  But what is true and what has her mind made up?  It is a page turner and when one of the characters goes missing it keeps you up at night trying to reach the conclusion.  A good one.  Well worth it.');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32069, 202129, 1, 'I purchased this book for a book club I joined and needless to say I finished it before the set date we were to discuss it. This story kept my attention from beginning to end. I loved how the story is told from the three women perspectives so you gain a full understanding of how they are connected. For a while I had a couple people in mind as the murders when I got closer to the end and realized neither of the people I suspected to be the murderer I was quite surprised. I read a couple reviews stating that they expected the story to end the way it did but I beg to differ. I didn''t feel like this was a typical story of love and betrayal. If you do decide to read this book I honestly don''t think you will be disappointed because I certainly wasn''t.');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32070, 202114, 2, 'Although it did get a bit old try to remember through an alcoholics memory. I guessed the killer long before Rachel pieced it together. Her unraveling of the story was slow and tedious at times. I''m not quite sure I would compare this book with Gone Girl as that story blew me away with the shear attention to detail. But this story was griping in its own right. I do have to say that I hated Anna but found the ending very satisfying. It was a quick read and I would recommend it for what it is.');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32071, 202123, 3, 'I could not put this book down it was such an amazing novel. I would definitely recommend this to people who love a good mystery.');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32072, 202118, 5, 'I just have to say that overall I think that this is a very well written story and it definitely had a lot of twists and turns that we all want. On the other hand, my only problem is that I feel like all of the main characters, Rachel especially, were completely irrational with nearly all of their decisions through out the whole book, and it basically made me want to hurry up and finish the story when I wasn''t even halfway done because it became unbearable.I think that an interesting character has to be a bit crazy, but there also has to be a bit of sanity to balance it out, and i believe if the author had done that, then the story would have been a lot stronger.');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32073, 202112, 3, 'I am a young adult who is very much just into to reading the average young adult romance. This book, however, took me away from my norm and was surprisingly much more engaging than my usual. This book takes you from suspense to heartbreak to confusion  in seconds and you almost feel that you are the character experiencing these events. I would recommend this to anyone who loves a mystery with a different flare but I would also recommend this to young adults like me who are looking for an incredible book that may not be what you''re used to but that is worth straying from that norm to read.');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32074, 202108, 4, 'Loved it! The beginning was very dark but soon weaved into a super suspenseful read - some mysteries have so many seemingly unrelated details that have to come together that you  reread previous pages- this was just the right mix of mystery, without being too complicated.  Can''t  wait for the movie-');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32075, 202144, 3, 'I was intrigued with the storyline because it kept me guessing until the end. However, I just was not enjoying the narrative. It seemed to lack, for a better word, intensity.  It was like watching a  great play with poor acting.');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32076, 202109, 2, 'Chiefly because of the alternating persons format and partly due to back and forth time switches the book was a little hard to follow when you read as I do...a chapter here; a few pages there. But overall I found it an engaging read.  As a recovering alcoholic myself I found it interesting that several of the characters showed strong signs of the disease.');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32077, 202124, 3, 'For me, this is a new genre of mystery/thrillers, along the lines of Gone Girl. I like it. The characters are well developed, although I never did really understand what Megan''s problem was. Was she bipolar? Narcissistic? In any case Rachel certainly was a tragedy, but in the end she redeemed herself, which I applaud. Like a train, this book chugged steadily along gathering speed at times and screeching to a stop at others. I couldn''t put it down. There was just too much to discover and the desire to find out what happens next, undeniable.');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32078, 202135, 2, 'I found The Girl on the Train a redundant read expecting a climax that didn''t arrive. The protagonists path and her interminable ruminating on her train rides, I felt deserved a more satisfying ending. For me it read, like a long short story. Traveling through life using a vehicle like a train seemed such a good idea...');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32079, 202132, 1, 'I thought it was good but it took me a while to get through because I kept getting confused.');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32080, 202133, 3, 'It''s probably not a good idea for me to review this book. From the fact that it is on the best seller list shows how well received it must be by readers. I personally found it very well written but much too dark for me. I was depressed the entire time I was reading it. The character doesn''t have a redeeming quality. She''s a falling down drunk and makes no attempt to help herself. How her friend could have been so patient after she threw up in the foyer didn''t ring true to me at all.  I think for many people that would have done it.');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32081, 202101, 1, 'It''s a hard one to ever put day');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32082, 202140, 2, 'The twist(s) was good, but the build up was slow, slow, slow. The protagonist is unsympathetic, but as an alcoholic I suppose that was the intent. Keep reading despite the plodding pace and mewling main character -- the ending is properly satisfying.');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32083, 202124, 3, 'The book is poorly written.  It moves from one character speaking to another and all the characters spark in the same voice.  The last third of the book becomes more interesting, but I knew who the murderer was by about half way through.  I read it for my book club.  If you don,t have to read it, skip it.');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32084, 202106, 1, 'This book was very riveting!!  I read it in about a day and a half.  Kept me turning the pages, and that''s something because I haven''t picked up a book in 2 years that I hadn''t stopped reading in the middle.');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32085, 202121, 5, 'Although it got better at the end, this was a difficult book to motivate myself to read.  It moves slowly, and the reader has to keep flipping back to check the dates of the sections.  I could not identify or empathize or even sympathize with any of the characters.');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32086, 202118, 1, 'Suspenseful but not the best writing I''ve ever read. I found the switch from one character''s actions to the other, along with some writing faux pas to be distracting. Near the end, when the tension was building, the main character was described as sitting in an expensive, leather chair she had bought, but soon afterward she was described as being on the sofa. The author went to the trouble of describing the chair, but never mentioned any action saying the character had moved.');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32087, 202132, 4, 'Absolutely LOVED this book  Amazing beginning to end.  Now I need to see the movie!');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32088, 202149, 2, 'This is the first novel by Paula Hawkins that I have read.  It certainly won''t be the last!This is a brilliantly crafted story, told by multiple characters, all of whom are unwillingly woven into this web of mystery.Rachael, the drunken ex-wife of Tom seems to be the first one to begin to  "stir" this story that will keep you glued to its pages right up to the end.  Be patient in the beginning, when all the characters are having their say about this "stew."  You won''t regret it!');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32089, 202103, 3, 'Although I did figure out some of the plot lines, I still found it very compelling and it definitely was hard to put down.  I know the movie is coming out soon so I''m glad I got to read it before seeing the movie--although since I saw the trailer before I read the book, it kind of ruined my own image of the main character.');
insert into REVIEWS (id, ISSUE_ID, RATING, REVIEW) values (32090, 202114, 4, 'I enjoyed the intrigue of looking into the lives of the couples from the girl on the train as at first she seemed just an objective observer going to and from work while riding the train as any commuter does on a daily basis. Then the intrigue grows into great suspense as the girl on the train not only is revealed as a former family member of one of those couples, but the reader becomes the sleuth trying to solve the mystery. I had to force myself to turn the light off, stop reading, and go to bed.');
