create table REVIEWS (
	id INT PRIMARY KEY,
	ISSUE_ID INT,
	USER_ID INT,
	BOOK_ID BIGINT,
	RATING INT,
	REVIEW VARCHAR(6000),
	FOREIGN KEY(ISSUE_ID) REFERENCES ISSUES(id),
	FOREIGN KEY(USER_ID) REFERENCES USERS(id),
	FOREIGN KEY(BOOK_ID) REFERENCES BOOKS(isbn)
);
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32056, 202101, 70, 8283310000000, 1, 'Wow!  I''ve read the glowing reviews, I know it''s sold a bazillion copies, and it''s probably only a matter of time before it''s a Nicole Kidman movie.....but I don''t get what''s the big deal here.  For me, the novel only kicked into high gear during the last quarter. Up to then, though, it was very slow going.  If it hadn''t  been for all those reviews, I''d have given up on it before I even reached that last quarter.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32057, 202102, 103, 8606200000000, 2, 'I enjoyed reading Gone Girl and this was recommended as a similar book that I would like. I did enjoy it, but it was a little slow going and slightly predictable. I prefer more plot twists and being surprised, and this book did not really surprise me. It also wrapped up a little too quickly and neatly, but I feel that way about a lot of books (such as Gone Girl and Luckiest Girl Alive). Would recommend to others for sure, but did not love it and would not re-read it again.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32058, 202103, 23, 8644590000000, 1, 'The narrative made the story interesting, but many characters were underdeveloped. The twist was predictable, but once there was revelation the story closed without fulfilment.  Worth the effort.  I think the movie will be grand, but don''t read the story first.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32059, 202104, 51, 8550610000000, 1, 'Thrilling page turner. Although it took me a while to catch on to the chapter structure of the book, in the end it was a brilliant hook that kept the plot twists coming in fresh waves of deceit.Set in England, focusing on nos. 15 and 23 Blenheim Road along an active set of commuter railroad tracks; Rachel Watson has a daily fixation on the people she sees living out their lives along the tracks as she travels in to town for work. Until one day the daily routine of bliss and serenity goes dark. Rachel finds herself caught up in the swirling ebb and flow of deceit as she finds herself pulled into the middle of a missing persons investigation.I found the unique [to me anyway] chapter structure engaging, serving as a series of flashbacks and among the series of first person accounts that drive the story forward. I shudder to think just how real and probable this plot can be. The human mind and the heart that drives it is so very depraved that the evil depicted in this story is very believable.While I don''t mind a bit of profane language in a story where it''s a real world situational necessity - soldiers swear in combat, lovers loose their tongue when in the heat of discord, etc. - the language got a bit rough toward the end which was a bit of a turn off for me. Beyond that, I found the book enjoyable. Beautifully edited, there are some spots where the ''British English'' served well to remind me of the book''s setting...not in my American neighborhood.Bravo Paula Hawkins on a contemporary work of art that will certainly stand the test of time.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32060, 202105, 1, 8918330000000, 5, 'I bought this book when Hurricane Matthew came into town. Hoping to hunker down with a good book. It''s been two weeks since the hurricane and I can''t get thru half of the book. It''s horrible, predictable, slow and depressing. This is all i have to say. Do not waste your money...maybe the movie will be better.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32061, 202106, 101, 8702510000000, 4, 'Excellent read!');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32062, 202107, 136, 8619910000000, 2, 'This book is pretty much on target for a classic movie, I would compare it to some of my all time favorites, Cape Fear, Gone Girl. I would suggest reading by anyone that gets into a good book, and can''t put it down. That''s the kind of book this is.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32063, 202108, 68, 8126050000000, 2, 'This is the kind of book where you want to reach into the pages and wring the protagonist''s neck!  I shouted at her; I ranted; I raved, but she didn''t listen.  She just continued on her path of self-destruction and dragged me along for the ride.  Plenty of twists and turns, just like the train ride, and just want you think you know what''s going to happen next ... the plot changes!  Reads quickly and is spell-binding.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32064, 202109, 23, 8953340000000, 2, 'It''s been a long time since I''ve been able to finish a book because the author seems to lose me in the middle--if not at the beginning. This one though, kept me hooked til the end! Can''t wait to see the movie, by I can''t imagine it topping the book.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32065, 202110, 148, 8554980000000, 5, 'I really enjoyed the book - it does have a sort of ''Gone Girl'' feel, but I liked that book too.  I think the characters are interesting and although I did figure out a portion of the ending, I had to keep reading to see if I was correct.  This was a book club read and I think there is plenty to discuss at our meeting.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32066, 202111, 44, 8446020000000, 3, 'I bought this book when Hurricane Matthew came into town. Hoping to hunker down with a good book. It''s been two weeks since the hurricane and I can''t get thru half of the book. It''s horrible, predictable, slow and depressing. This is all i have to say. Do not waste your money...maybe the movie will be better.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32067, 202112, 26, 8744830000000, 5, 'This story will shake you to your core. I absolutely couldn''t put this down. Whatever you think you know, or remember will only seem like a dream when you come to the last page of this thrilling, nightmarish story. You won''t look at people or their lives the same way ever again. If you''re looking for some thing to get lost and carried away in, look no further. Anna will tell you what happened that day on the train.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32068, 202113, 124, 8355250000000, 2, 'This novel has gotten a lot of hype so I was curious to read it. BTW, I have been an English teacher for years, majored in English in college and normally do not read popular novels. So, I decided that I would read the whole thing to the end, which I did. The final chapters of the novel did reveal a clever twist or two, but the majority of the novel, in my opinion, needed a good editor. So much of the novel is repetition--getting drunk, doing something, not remembering it, etc. that after a while, it became boring to me. But, there were some good twists and turns to the plot--enough to keep me reading--so if you want a well written novel that would compare with Le Carre or Silva, turn this one down. But, if you like a roller coaster read and can just skip the reiterating of the same old problems over and over to get the the fun stuff, go for it.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32069, 202114, 120, 8960380000000, 2, 'I found this book tedious in the extreme.  Not fast-paced, not a thriller.  The characters weren''t relatable, they were boring.  The alcoholism was grating, and far too repetitively convenient as a plot point.  I''m giving it two stars because the writing was decent -- not compelling, but Ms. Hawkins knows how to put sentences together and has a decent command of grammar, a skill not shared by a lot of current authors.  Her plotting is another matter. The overall plot wasn''t bad, but along the lines of what another reviewer wrote, instead of putting the effort required into writing a truly engaging story with unfolding events, the author just had her narrators withhold detail so she could have a series of plot twists.  I knew who the killer was halfway through the book.  The final twist was the most satisfying, but it was an effort to finish the book to get to it.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32070, 202115, 19, 8293010000000, 5, 'Overall liked the book - but it is not something I would re-visit as (1) There is not too much sub-text or character details that I want to re-visit after the reveal and  **spoilers ahead**(2) though there is some attempt at describing and analyzing issues related to infertility, baby death, alcoholism, the author does not dig too deeply to surface the complexity around them. For e.g. it would have been great to know more about the killer - not the motivation, which was clearly laid out, but just more about the killer''s tastes, personality, etc.The multiple narrator touch seems to be a new thing in literature, especially the unreliable-female-narrator. It works for a larger extent, but of course, I can sense the struggle that the author might go through with trying not to reveal too many spoilers.Recommended for its good premise and pace. Made some difficult reading for me as some of the issues mentioned drove home.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32071, 202116, 92, 8289920000000, 4, 'The first half of this book is very complicated, confusing, and rather slow to develop into a "don''t stop until you finish" final.  I haven''t had a chance to see the movie, but I know they won''t be able to catch the different thought patterns of the main character.  Very detailed plot hard to follow at times; complicated, intertwined characters; dialogue (5 on a scale of 10.  It is a rather dreary read at times.SPOILER ALERT:  I have dealt with alcoholics in my past and it was painful to have the main character struggling so much with alcohol.  Several times I almost put it down because of the bad feelings it engendered.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32072, 202117, 78, 8569980000000, 5, 'This book was very riveting!!  I read it in about a day and a half.  Kept me turning the pages, and that''s something because I haven''t picked up a book in 2 years that I hadn''t stopped reading in the middle.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32073, 202118, 194, 8244750000000, 5, 'I liked to mystery of the whole book. I usually don''t care for mysteries but it was a part of our book club selection so I braved the way to reading. I''m very glad that I did. Very few characters but each well thought out and creatively woven together.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32074, 202119, 114, 8593510000000, 3, 'This book was pretty amazing, despite the lack of characters that I could relate to or even like. This book has similarities to Gone Girl, but there''s so much more to it. Halfway through the book was when it started to get good, and honestly I rushed it these last few days just because I wanted to watch the movie. Overall, I''m glad I read it and the end was shocking to me!');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32075, 202120, 170, 8720700000000, 1, 'Honestly I do not understand how this book gets on and stays on the best seller list!It is really ho-hum----and some of the books on the BS list have been there so longwhile others (new ones) get passed over.  Really have never understood their wayof chosing.  Now, one that is wonderful is "All the Light that ever was"---aninspiring story and lovely writing.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32076, 202121, 36, 8272540000000, 1, 'Everyday, Rachel takes the train to work. As the train comes to halt at a signal, she daydreams about the people in the houses she sees. She watches the moments of their lives that she observes from the train, and she makes up stories about them. This is merely daydreaming, until the day she witnesses something. Then, everything changes!As I read this, I kept thinking about that voyeuristic quality that I enjoyed in Hitchcocks REAR WINDOW. We all seem to enjoy looking into other peoples lives and catching a glimpse of what a strangers private life might be like.This book kept me guessing until the last minute. Because the author narrated different chapters in the first person by three alternating characters, we are able to get to know them from the inside out, understand how their minds work, and see how they evolve as the tension of the murder mystery builds. This is a very clever way to both allow the reader to relate to the characters and their feelings, as well as to tell a story from varying viewpoints. I bet you cant put this one down! I couldnt!');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32077, 202122, 85, 8277690000000, 3, 'I agree with some other reviewers. The characters in this novel were all annoying and not believable.  The main character, Rachel, you just want to reach out and smack some sense into her.  I just keep reading so I could be done with it. It is one crazy female after another, surrounded by awful men. I fail to see why this book is getting so many good reviews. Stay away.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32078, 202123, 12, 8603470000000, 1, 'This book required a little time on my part to easily go back and forth between the first person accounts of the story from the 2 main characters. I sometimes had to go back and remind myself of who was speaking at a particular point. I also found the psychological problems of one of the main characters not pursued enough to explain the reasons why she did what she did. Aside from those 2 things, I liked the book very much.  I loved the use of the "train" in telling the story. The ending was somewhat of a surprise to me which is good---I don''t like to figure it out ahead of time. I would recommend the book for those who like to think versus be entertained.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32079, 202124, 131, 8366520000000, 3, 'It was an easy summer read. It was not the best mystery novel written...and the characters were a pretty one note. But I was looking for a quick summer read and this fit the bill. The writing was good and the plot kept me in it...I was fairly certain I knew who did it early on but nevertheless it was worth the read. I would give it 3 1/ 2 stars if I could.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32080, 202125, 7, 8761950000000, 2, 'This is a book that intrigued me from the outset.  The main character seems to be so weak and disturbed, but I found myself rooting for her anyway, wanting her to get herself straightened out.  I didn''t know when I began reading that the book is a whodunnit, and I kept changing my mind about the identity of the perpetrator.  The author did a wonderful job of revealing the various stories of each of the players and their parts in the mystery.  She kept me in suspense.  I would recommend this book to anyone who likes a murder mystery.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32081, 202126, 123, 8654260000000, 1, 'If you like thrillers or crime stories this will be a good choice for you. One of the better books I''ve read. Typically I go for non fiction but this was a very entertaining book. Now I want to see the movie!');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32082, 202127, 164, 8357830000000, 2, 'Overall, This book was simply OK. The main character, Rachel, was enough to make you want to scream. I can''t imagine someone being as dim witted as this one. If you have the chance to read this book free of charge, give it a try. Definitely not worth the $10 I paid for it though.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32083, 202128, 120, 8601130000000, 5, 'An unreliable blackout alcoholic narrator. She can not stay away from her ex. She doesn''t remember details, but she was in the area when the second wife disappeared. She keeps having sex with suspects. She blabs what she thinks she knows to the wrong people. She''s an every woman in search of what went so terribly wrong to this woman and to herself. I really enjoyed this book!');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32084, 202129, 143, 8875290000000, 3, 'This story is narrated from the viewpoint of three women. The author jumps between them and time frames sliding from the current time to past. I found it rather cumbersome but, at the insistence of my daughter, I kept reading. It did get better around the middle of the book. Unfortunately, by then I had a really good idea who caused all the havoc.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32085, 202130, 48, 8938460000000, 1, 'One of the best books I''ve read this year.  I loved the first person narration--by three different narrators.  The women''s stories start at different points in time and converge at the end of the novel.  (Watch the narrator and dates on each chapter as you read.)  Perhaps the most original murder mystery I have ever read.  I would say more, but I don''t want to give anything away!');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32086, 202131, 31, 8823000000000, 3, 'I enjoyed reading this book and I was surprised by the ending. That being said, when the author doesn''t develop the antagonist, the twist is expected. All the females were interesting but I wish the author had developed the men''s characters in the same way.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32087, 202132, 184, 8596700000000, 4, 'This is one of the best books I have read in a long time.  It was a page turning psychological thriller that was hard to put down and can easily finished in a day or afternoon of reading.  The main character, Rachel, is somewhat of a sad case that has not gotten over her failed marriage to Tom, who has moved on with another woman, Anna and recently had a child (something she was unable to give him).  As if the divorce and her inability to have children is not enough, Rachel is constantly reminded of Toms new life without her every day as she passes by their home that was once hers on the train each day.  She is obsessed with them and their neighbor Megan and her husband.  The story is told from the perspective of the three women; Rachel, Anna and Megan.  As Rachels life continues to disintegrate throughout the novel, her obsession with the couples along with her drinking problem continues to get worse.  As her life falls apart, she becomes engrossed with Megans disappearance and trying to solve what happened to her.  With the three perspective stories the reader is left trying to figure out what eventually happens to Megan upon her disappearance and how all three women are connected.  The climax and ending of the book is truly shocking and will leave you wanting more from Paula Hawkins.  The plot would make an excellent movie and I am looking forward to more work from this author.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32088, 202133, 85, 8599340000000, 3, 'This novel has gotten a lot of hype so I was curious to read it. BTW, I have been an English teacher for years, majored in English in college and normally do not read popular novels. So, I decided that I would read the whole thing to the end, which I did. The final chapters of the novel did reveal a clever twist or two, but the majority of the novel, in my opinion, needed a good editor. So much of the novel is repetition--getting drunk, doing something, not remembering it, etc. that after a while, it became boring to me. But, there were some good twists and turns to the plot--enough to keep me reading--so if you want a well written novel that would compare with Le Carre or Silva, turn this one down. But, if you like a roller coaster read and can just skip the reiterating of the same old problems over and over to get the the fun stuff, go for it.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32089, 202134, 174, 8420080000000, 2, 'An "OK" book, just moved too slowly. I hope the movie is better.');
insert into REVIEWS (id, ISSUE_ID, USER_ID, BOOK_ID, RATING, REVIEW) values (32090, 202135, 127, 8482170000000, 1, 'I only gave four stars because of the uncomfort
